### ISSUE TITLE
Cannot handle unknown node `raw` on Docusaurus v3

### ISSUE THREAD

**Issue by Amgelo563** [nice-move/remark-kroki#4]
When adding a diagram on Docusaurus 3.0.0, the following error is thrown when rendering the doc that contains said diagram:
```
Module build failed (from ../../node_modules/.pnpm/@docusaurus+mdx-loader@3.0.0_@docusaurus+types@3.0.0_esbuild@0.18.20_react-dom@18.2.0_react@18.2.0/node_modules/@docusaurus/mdx-loader/lib/index.js):
Error: MDX compilation failed for file "D:\Projects\nyx\apps\docs\docs\features\commands\command-overview.mdx"
Cause: Cannot handle unknown node `raw`
Details:
Error: Cannot handle unknown node `raw`
    at unknown (file:///D:/Projects/nyx/node_modules/.pnpm/hast-util-to-estree@3.1.0/node_modules/hast-util-to-estree/lib/state.js:197:9)
    at one (file:///D:/Projects/nyx/node_modules/.pnpm/zwitch@2.0.4/node_modules/zwitch/index.js:108:17)
    at Object.handle (file:///D:/Projects/nyx/node_modules/.pnpm/hast-util-to-estree@3.1.0/node_modules/hast-util-to-estree/lib/state.js:170:12)
    at Object.all (file:///D:/Projects/nyx/node_modules/.pnpm/hast-util-to-estree@3.1.0/node_modules/hast-util-to-estree/lib/state.js:225:25)
    at root (file:///D:/Projects/nyx/node_modules/.pnpm/hast-util-to-estree@3.1.0/node_modules/hast-util-to-estree/lib/handlers/root.js:26:26)
    at one (file:///D:/Projects/nyx/node_modules/.pnpm/zwitch@2.0.4/node_modules/zwitch/index.js:108:17)
    at Object.handle (file:///D:/Projects/nyx/node_modules/.pnpm/hast-util-to-estree@3.1.0/node_modules/hast-util-to-estree/lib/state.js:170:12)
    at toEstree (file:///D:/Projects/nyx/node_modules/.pnpm/hast-util-to-estree@3.1.0/node_modules/hast-util-to-estree/lib/index.js:72:22)
    at file:///D:/Projects/nyx/node_modules/.pnpm/@mdx-js+mdx@3.0.0/node_modules/@mdx-js/mdx/lib/plugin/rehype-recma.js:28:12
    at wrapped (file:///D:/Projects/nyx/node_modules/.pnpm/trough@2.1.0/node_modules/trough/index.js:115:27)
    at next (file:///D:/Projects/nyx/node_modules/.pnpm/trough@2.1.0/node_modules/trough/index.js:65:23)
    at done (file:///D:/Projects/nyx/node_modules/.pnpm/trough@2.1.0/node_modules/trough/index.js:148:7)
    at then (file:///D:/Projects/nyx/node_modules/.pnpm/trough@2.1.0/node_modules/trough/index.js:158:5)
    at wrapped (file:///D:/Projects/nyx/node_modules/.pnpm/trough@2.1.0/node_modules/trough/index.js:136:9)
    at next (file:///D:/Projects/nyx/node_modules/.pnpm/trough@2.1.0/node_modules/trough/index.js:65:23)
    at done (file:///D:/Projects/nyx/node_modules/.pnpm/trough@2.1.0/node_modules/trough/index.js:148:7)
    at then (file:///D:/Projects/nyx/node_modules/.pnpm/trough@2.1.0/node_modules/trough/index.js:158:5)
    at Object.mdxLoader (D:\Projects\nyx\node_modules\.pnpm\@docusaurus+mdx-loader@3.0.0_@docusaurus+types@3.0.0_esbuild@0.18.20_react-dom@18.2.0_react@18.2.0\node_modules\@docusaurus\mdx-loader\lib\loader.js:126:25)
```
The error seems to happen for every output type except `img-base64`, where it renders fine.

**Comment by Airkro** [comment]
Not support mdx yet, please wait.

But this plugin still can work on Docusaurus v3 when a file extname detect to `md`.

```js
// docusaurus.config.js
export default {
  markdown: {
    format: 'detect',
  },
};
```

See: https://docusaurus.io/docs/api/docusaurus-config#markdown

**Comment by Amgelo563** [comment]
I see, using `.md` does fix the error, but then I can't use mdx features. The plugin used to work fine for `.mdx`, so I assume it's an issue with new libraries. I'll wait for the plugin to add support for it then, thanks!

**Comment by Airkro** [comment]
I have published [v0.3.0](https://www.npmjs.com/package/remark-kroki/v/0.3.0) to support MDX@3.0

Now this plugin can work with Docusaurus v3, please send me feedback.

**Comment by Amgelo563** [comment]
It now compiles, however I use `img-html-base64`, and I had to change my CSS selector to select the `data-type` attribute, since now the image doesn't have the `kroki-image` class anymore.

Old (not working anymore):
```css
.kroki-image {
  /* Styles */
}
```

New (works):
```css
[data-type='plantuml'] {
  /* Styles */
}
```

Not sure if this is intended or not, just mentioning it just in case. If it is intended, consider this issue solved, thanks!

**Comment by Airkro** [comment]
[v0.3.1](https://www.npmjs.com/package/remark-kroki/v/0.3.1) now fix it.

**Comment by jaune162** [comment]
docusaurus 3.2.1
remark-kroki 0.3.6
output : `inline-svg`

Get this error again.

This error still exists after run command `docusaurus clear`

**Comment by Airkro** [comment]
Have you read the https://github.com/show-docs/remark-kroki#troubleshooting document? 

For now, mode `mdx3` and `inline-svg` need the `rehype-raw` plugin
